module HealthSeven::V2_3
autoload :CMCcp, File.dirname(__FILE__) + '/base_datatypes/cm_ccp.rb'
autoload :CMCdElectrode, File.dirname(__FILE__) + '/base_datatypes/cm_cd_electrode.rb'
autoload :CMCsu, File.dirname(__FILE__) + '/base_datatypes/cm_csu.rb'
autoload :CMMdv, File.dirname(__FILE__) + '/base_datatypes/cm_mdv.rb'
autoload :CMOsd, File.dirname(__FILE__) + '/base_datatypes/cm_osd.rb'
autoload :DT, File.dirname(__FILE__) + '/base_datatypes/dt.rb'
autoload :ID, File.dirname(__FILE__) + '/base_datatypes/id.rb'
autoload :IS, File.dirname(__FILE__) + '/base_datatypes/is.rb'
autoload :NM, File.dirname(__FILE__) + '/base_datatypes/nm.rb'
autoload :SI, File.dirname(__FILE__) + '/base_datatypes/si.rb'
autoload :ST, File.dirname(__FILE__) + '/base_datatypes/st.rb'
autoload :TM, File.dirname(__FILE__) + '/base_datatypes/tm.rb'
autoload :TN, File.dirname(__FILE__) + '/base_datatypes/tn.rb'
end
